[tool.poetry]
name = "sort_destination"
version = "0.1.0"
description = ""
authors = ["Nojima Masanari <mnojima0923@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
flake8 = "^3.8.3"
requests = "^2.24.0"
autopep8 = "^1.5.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
